eywaUri=https://eywa.int.creditsaison.corp
protiumUri=https://ckyc.int.creditsaison.corp
silverSurferUri = https://silversurfer.int.creditsaison.corp
bureauengine = https://bureauengine.int.creditsaison.corp
