eywaUri=https://eywa.qa2.creditsaison.corp
protiumUri=https://ckyc.qa2.creditsaison.corp
silverSurferUri = https://silversurfer.qa2.creditsaison.corp
dbUrl = jdbc:postgresql://localhost:3432/proddb
dbUsername = masteruser
dbPassword = JtIFpXIj4HsqLip
command = ssh -vvv -N -L 3432:ksf-cluster-v2-eu-west-1.cluster-czamg4embzqn.eu-west-1.rds.amazonaws.com:5432 bastion-qa2
bureauengine = https://bureauengine.qa2.creditsaison.corp