eywaUri=https://eywa.uat.creditsaison.corp
protiumUri=https://ckyc.uat.creditsaison.corp
silverSurferUri = https://silversurfer.uat.creditsaison.corp
bureauengine = https://bureauengine.uat.creditsaison.corp
dbUrl = jdbc:postgresql://localhost:9432/proddb
dbUsername = masteruser
dbPassword = bZPjPVV6jcp7cjS
command = ssh -vN -L 9432:ksf-cluster-v2-us-east-1.cluster-ciadyfvxwwzl.us-east-1.rds.amazonaws.com:5432 bastion-uat-ksf