extent.reporter.spark.start=true
extent.reporter.spark.out=cyborg_report.html
extent.reporter.spark.config=src/test/resources/extent-config.xml
basefolder.name=common-platform
systeminfo.DoneBy = cyborg
systeminfo.Team = Omega QA